// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjD1MG6WFw62zzHBlp0kFuSa1xGTo9T_k',
    appId: '1:956753787128:web:46b19f8711cedd4a9b230d',
    messagingSenderId: '956753787128',
    projectId: 'sample-project-72cda',
    authDomain: 'sample-project-72cda.firebaseapp.com',
    storageBucket: 'sample-project-72cda.appspot.com',
    measurementId: 'G-75MR8TJ4W6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHdyfqYGjigZGs8ZWX16G8KgbdNHXVoRE',
    appId: '1:956753787128:android:c7d6e5cdb14fc1019b230d',
    messagingSenderId: '956753787128',
    projectId: 'sample-project-72cda',
    storageBucket: 'sample-project-72cda.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxQXIXoKvdMhmawoCk3SZzU6OTZR0liDo',
    appId: '1:956753787128:ios:66ca8899c9dfec2a9b230d',
    messagingSenderId: '956753787128',
    projectId: 'sample-project-72cda',
    storageBucket: 'sample-project-72cda.appspot.com',
    iosClientId: '956753787128-dk35rbankqmb05lbi4tpngaj4bfcv83i.apps.googleusercontent.com',
    iosBundleId: 'com.example.personalMoneyManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxQXIXoKvdMhmawoCk3SZzU6OTZR0liDo',
    appId: '1:956753787128:ios:66ca8899c9dfec2a9b230d',
    messagingSenderId: '956753787128',
    projectId: 'sample-project-72cda',
    storageBucket: 'sample-project-72cda.appspot.com',
    iosClientId: '956753787128-dk35rbankqmb05lbi4tpngaj4bfcv83i.apps.googleusercontent.com',
    iosBundleId: 'com.example.personalMoneyManager',
  );
}
